CREATE TABLE course (
    id INT PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    code VARCHAR(5) NOT NULL,
    dept_name VARCHAR(50) NOT NULL,
    FOREIGN KEY (dept_name) REFERENCES department(name) ON DELETE CASCADE
);